site_name: Twilio Agent Connect Python SDK
site_url: https://twilio.github.io/twilio-agent-connect-python/
repo_url: https://github.com/twilio/twilio-agent-connect-python

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            filters:
              - "!^_"
              - "!^model_"
            show_if_no_docstring: false

nav:
  - Home: index.md
  - API Reference: api.md
